language: java
script:
- mvn javadoc:javadoc
after_success:
- "./push-javadoc.sh"
dd:
  secure: gOkGDiQqrDwpkwi4ZlcU6g1R82XK+bWXelPZjzGtDpSIJJNDGfuRwmnj6/gZqZgDHZ6VP7bBdUblYGWH0Bsy63kIdGvuD8voAD+fmGRW1aLlyK51tZJ6g93z1Z/6N7eY+HbA26RWh5mocsBDkLTHZ0vM6wk+o+Jo21lqwcGQXtoRuBnLwD/d4hFk+nfLXSalVRA1RHqbHvXmA8KY3OFvUZ/XOqNfDTSVgjSaceCdKRUezZpvilffhFmnZWwL3OKUoehax8uH3naPGm/0C6QfQpn2zwtzTZXlP7NA9Ft/g0GdiZi5+LKbpKac+C1SBH61KflGR43NFNfSQK4Wm2gqLz7jSRGLrE9NdXnWopoaO0X2D1p+qw+yELBFsOoUvhgxMmozhLE7Al4smG0e1RaH0RPB6lpDjDvZWvJzFe5IICPjlHuQSG/JW/AxM0U4EsQjscvYzYHm4RT/qYe/IYUepF2StyNXOmG4X/Ij3UG9lbvnPTx46QLJj/nMQ77zp+uvgmqwVfSf/LF92Kp26k/QBWnt3W3uhkEwUEFx9HutkruX7xCOOeFHoAb+wV2ymsbhZYNv7eLR/IgxRgPd1UycC7eFg48JIoIT6RFhMBcjvN4pJwXg9pwLupjJjh5qCegxcCUorjHBNpKo+WA8mJFz6bP4cTzDMei5pNeH8/EPsbU=
